### PR TITLE
Create nice.js

### PR DESCRIPTION
**Pull request by mzeeshan7100**

### CODE REVIEW

**Review by mzeeshan3597 — COMMENTED** [review]
so sorry... no more need this pollyfil

**Comment by mzeeshan3597** [comment]
i have deleted unused extra branch

**Comment by mzeeshan7100** [comment]
now we have got and issue... and only way to resolve it by adding pollyfil

**Review by mzeeshan3597 — APPROVED** [review]
approved

**Comment by mzeeshan3597** [comment]
merged and branch deleted

**Comment by mzeeshan3597** [comment]
wow.... appreciated

**Pull request merged**
